#include<stdio.h>

int main()
{
/*	printf("aaaaaaaaaaaaaaaa\nsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss\nddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd\nffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ngggggggggggggggggggggggggggggggggggggggggggggggg\nhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh\njjjjjjjjjjjjjjjjjjjjjjjjjjjjj\nkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk\nllllllllllllllllllllllllllllllll\nzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\nccccccccccccccccccccccccccccccccccccccccc\nvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv\nvbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\nbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\nmmmmmmmmmmmmmmmmmmmmmmm\nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn\nqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq\nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww\neeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee\nrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr\nttttttttttttttttttttttttttttttt\nyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy\nuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu\niiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii\niiiiiiiiiiiiiiiiiii\noooooooooooooooooooooooooooooooooooooooooooooo\noppppppppppppppppppppppppppppppppppppppppppppppppppppppp\n1234567890-1234567890pwertyuiop54r3eqwdfgbhjmkuil9o7865432rqwefgrtyu1234567890123456789111111111111111111111111111111111111111111111111\n");
	*/
	int num;
	scanf("%d", &num);
	printf("%d", num);
	int ch;
	scanf("%d", &ch);
	printf("hiiiiiiiii");
	printf();
	return 0;
}
